services:
  - type: web
    name: nexus-backend
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/LeoRamirez1405/hogwarts-nexus-lumiere
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
