"""initial_schema_baseline

Revision ID: 23c12a9f568c
Revises: 
Create Date: 2026-08-03 17:39:15.043845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c12a9f568c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifieds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('ability', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('required_user_level', sa.Integer(), nullable=False),
    sa.Column('required_sanctuary_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enum_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enum_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enum_categories_code'), ['code'], unique=True)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pet_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('restore_amount', sa.Integer(), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('shop', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('weekly_sales', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('zerines', sa.Integer(), nullable=False),
    sa.Column('house_points', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('house', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('wand', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('official_title', sa.String(length=100), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('care_actions', sa.Integer(), nullable=False),
    sa.Column('items_purchased', sa.Integer(), nullable=False),
    sa.Column('sanctuary_penalty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created_at', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_id_created_at', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('chat_rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('join_approval', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enum_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['enum_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'label', name='uq_enum_value_category_label')
    )
    with op.batch_alter_table('enum_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enum_values_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enum_values_label'), ['label'], unique=False)

    op.create_table('event_visibility_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subscription_json', name='uq_user_subscription')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('safety_numbers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('remote_user_id', sa.String(), nullable=False),
    sa.Column('safety_number', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remote_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'remote_user_id', name='uq_safety_number_pair')
    )
    with op.batch_alter_table('safety_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_numbers_remote_user_id'), ['remote_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_numbers_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_conversation_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_type', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('last_message_id', sa.String(), nullable=True),
    sa.Column('last_message_body', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_sender_id', sa.String(), nullable=True),
    sa.Column('last_message_kind', sa.String(), nullable=True),
    sa.Column('last_message_attachment_url', sa.String(), nullable=True),
    sa.Column('last_message_attachment_type', sa.String(), nullable=True),
    sa.Column('last_message_attachment_name', sa.String(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_type', 'conversation_id', name='uq_user_conv_pref')
    )
    op.create_table('user_creatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('creature_id', sa.String(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('adopted_at', sa.DateTime(), nullable=False),
    sa.Column('last_decay_at', sa.DateTime(), nullable=True),
    sa.Column('farewell_warned', sa.Boolean(), nullable=False),
    sa.Column('attention_warned', sa.Boolean(), nullable=False),
    sa.Column('escaped_warned', sa.Boolean(), nullable=False),
    sa.Column('last_critical_at', sa.DateTime(), nullable=True),
    sa.Column('for_sale', sa.Boolean(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_identity_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('identity_key_public', sa.LargeBinary(), nullable=False),
    sa.Column('identity_key_private', sa.Text(), nullable=False),
    sa.Column('signing_key_public', sa.LargeBinary(), nullable=False),
    sa.Column('signing_key_private', sa.Text(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_identity_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identity_keys_user_id'), ['user_id'], unique=True)

    op.create_table('user_pet_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pet_item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_item_id'], ['pet_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_article')
    )
    op.create_table('chat_room_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_user')
    )
    op.create_table('forum_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_forum_thread_user')
    )
    op.create_table('forum_thread_votes',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('reply_to_id', sa.String(), nullable=True),
    sa.Column('forwarded_from_id', sa.String(), nullable=True),
    sa.Column('forwarded', sa.Boolean(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('disappear_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_type', sa.String(), nullable=True),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('e2e_encrypted', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['forwarded_from_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('post_reposts',
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('room_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_invites_token'), ['token'], unique=True)

    op.create_table('user_prekeys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('prekey_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['user_identity_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'prekey_id', name='uq_identity_prekey')
    )
    with op.batch_alter_table('user_prekeys', schema=None) as batch_op:
        batch_op.create_index('ix_prekeys_identity_used', ['identity_id', 'used'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prekeys_identity_id'), ['identity_id'], unique=False)

    op.create_table('user_signed_prekeys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('prekey_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['user_identity_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_signed_prekeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_signed_prekeys_identity_id'), ['identity_id'], unique=True)

    op.create_table('voice_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_channels_room_id'), ['room_id'], unique=False)

    op.create_table('encrypted_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('sender_ephemeral_public', sa.LargeBinary(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('previous_counter', sa.Integer(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encrypted_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encrypted_messages_message_id'), ['message_id'], unique=True)
        batch_op.create_index('ix_encrypted_messages_recipient_created', ['recipient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypted_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypted_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('location_type', sa.Enum('PHYSICAL', 'VOICE_CHANNEL', 'EXTERNAL_LINK', 'TEXT_ONLY', name='eventlocationtype'), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_url', sa.String(), nullable=True),
    sa.Column('voice_channel_id', sa.String(), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['voice_channel_id'], ['voice_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('message_reactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('multi_choice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('remote_user_id', sa.String(), nullable=False),
    sa.Column('remote_device_id', sa.String(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('local_identity_key_public', sa.LargeBinary(), nullable=True),
    sa.Column('local_base_key_public', sa.LargeBinary(), nullable=True),
    sa.Column('local_base_key_private', sa.Text(), nullable=True),
    sa.Column('remote_identity_key', sa.LargeBinary(), nullable=True),
    sa.Column('remote_base_key', sa.LargeBinary(), nullable=True),
    sa.Column('root_key', sa.LargeBinary(), nullable=True),
    sa.Column('sender_chain_key', sa.LargeBinary(), nullable=True),
    sa.Column('receiver_chain_key', sa.LargeBinary(), nullable=True),
    sa.Column('sender_ratchet_key_private', sa.Text(), nullable=True),
    sa.Column('sender_ratchet_key_public', sa.LargeBinary(), nullable=True),
    sa.Column('receiver_ratchet_key_public', sa.LargeBinary(), nullable=True),
    sa.Column('sending_message_count', sa.Integer(), nullable=False),
    sa.Column('receiving_message_count', sa.Integer(), nullable=False),
    sa.Column('previous_chain_length', sa.Integer(), nullable=False),
    sa.Column('has_sent_message', sa.Boolean(), nullable=False),
    sa.Column('prekey_id', sa.String(), nullable=True),
    sa.Column('signed_prekey_id', sa.String(), nullable=True),
    sa.Column('established', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prekey_id'], ['user_prekeys.id'], ),
    sa.ForeignKeyConstraint(['remote_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_prekey_id'], ['user_signed_prekeys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_established', ['established', 'archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_prekey_id'), ['prekey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_remote_user_id'), ['remote_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_signed_prekey_id'), ['signed_prekey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_user_remote', ['user_id', 'remote_user_id', 'remote_device_id'], unique=False)

    op.create_table('voice_channel_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('deafened', sa.Boolean(), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), nullable=False),
    sa.Column('screen_sharing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['voice_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_voice_channel_user')
    )
    with op.batch_alter_table('voice_channel_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_channel_participants_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_channel_participants_user_id'), ['user_id'], unique=False)

    op.create_table('event_reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reminder_time', sa.Enum('AT_TIME', 'MINUTES_15', 'HOUR_1', 'HOURS_3', 'DAY_1', 'DAYS_3', 'WEEK_1', name='remindertime'), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', 'reminder_time', name='uq_event_user_reminder')
    )
    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_reminders_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('event_rsvps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('GOING', 'MAYBE', 'NOT_GOING', name='rsvpstatus'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user_rsvp')
    )
    with op.batch_alter_table('event_rsvps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_rsvps_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_rsvps_user_id'), ['user_id'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('option_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_votes')
    op.drop_table('poll_options')
    with op.batch_alter_table('event_rsvps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_rsvps_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_rsvps_event_id'))

    op.drop_table('event_rsvps')
    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_reminders_event_id'))

    op.drop_table('event_reminders')
    with op.batch_alter_table('voice_channel_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_channel_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_voice_channel_participants_channel_id'))

    op.drop_table('voice_channel_participants')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_remote')
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_signed_prekey_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_remote_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_prekey_id'))
        batch_op.drop_index('ix_sessions_established')

    op.drop_table('sessions')
    op.drop_table('polls')
    op.drop_table('message_reactions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_events_room_id'))

    op.drop_table('events')
    with op.batch_alter_table('encrypted_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encrypted_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_encrypted_messages_recipient_id'))
        batch_op.drop_index('ix_encrypted_messages_recipient_created')
        batch_op.drop_index(batch_op.f('ix_encrypted_messages_message_id'))

    op.drop_table('encrypted_messages')
    with op.batch_alter_table('voice_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_channels_room_id'))

    op.drop_table('voice_channels')
    with op.batch_alter_table('user_signed_prekeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_signed_prekeys_identity_id'))

    op.drop_table('user_signed_prekeys')
    with op.batch_alter_table('user_prekeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prekeys_identity_id'))
        batch_op.drop_index('ix_prekeys_identity_used')

    op.drop_table('user_prekeys')
    with op.batch_alter_table('room_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_invites_token'))

    op.drop_table('room_invites')
    op.drop_table('post_reposts')
    op.drop_table('post_likes')
    op.drop_table('post_comments')
    op.drop_table('messages')
    op.drop_table('forum_thread_votes')
    op.drop_table('forum_subscriptions')
    op.drop_table('forum_comments')
    op.drop_table('chat_room_members')
    op.drop_table('article_subscriptions')
    op.drop_table('article_comments')
    op.drop_table('user_products')
    op.drop_table('user_pet_items')
    with op.batch_alter_table('user_identity_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identity_keys_user_id'))

    op.drop_table('user_identity_keys')
    op.drop_table('user_creatures')
    op.drop_table('user_conversation_preferences')
    op.drop_table('transactions')
    with op.batch_alter_table('safety_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_numbers_user_id'))
        batch_op.drop_index(batch_op.f('ix_safety_numbers_remote_user_id'))

    op.drop_table('safety_numbers')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    op.drop_table('posts')
    op.drop_table('notifications')
    op.drop_table('forum_threads')
    op.drop_table('event_visibility_settings')
    with op.batch_alter_table('enum_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enum_values_label'))
        batch_op.drop_index(batch_op.f('ix_enum_values_category_id'))

    op.drop_table('enum_values')
    op.drop_table('chat_rooms')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor_id_created_at')
        batch_op.drop_index('ix_audit_logs_action_created_at')

    op.drop_table('audit_logs')
    op.drop_table('articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('pet_items')
    op.drop_table('feature_flags')
    with op.batch_alter_table('enum_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enum_categories_code'))

    op.drop_table('enum_categories')
    op.drop_table('creatures')
    op.drop_table('classifieds')
    op.drop_table('announcements')
    # ### end Alembic commands ###