"""add fcm_token table

Revision ID: 48c91a54afa5
Revises: b3680516518b
Create Date: 2026-08-17 18:23:41.330072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c91a54afa5'
down_revision: Union[str, None] = 'b3680516518b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_user_fcm_token')
    )
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fcm_tokens_token'), ['token'], unique=False)
        batch_op.create_index('ix_fcm_tokens_user_active', ['user_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fcm_tokens_user_id'), ['user_id'], unique=False)

    op.drop_table('_alembic_tmp_user_cards')
    with op.batch_alter_table('article_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_comments_article_id'))

    with op.batch_alter_table('article_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_subscriptions_user_id'))

    with op.batch_alter_table('chat_room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_room_members_room_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_members_user_id'))

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_comments_thread_id'))

    with op.batch_alter_table('forum_thread_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_thread_votes_thread_id'))

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_threads_author_id'))

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_requests_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_friend_requests_sender_id'))

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_pinned'))
        batch_op.drop_index(batch_op.f('ix_messages_pinned_true'), sqlite_where=sa.text('pinned = 1'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id_unread'), sqlite_where=sa.text('read = 0'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_read'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_unread'), sqlite_where=sa.text('read = 0'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id_receiver_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_receiver_unread'), sqlite_where=sa.text('read = 0'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id_read'))

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_likes_user_id'))

    with op.batch_alter_table('post_reposts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reposts_post_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_shop_category'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_sender_id'))

    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.alter_column('foil',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('user_creatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_creatures_creature_id'))
        batch_op.drop_index(batch_op.f('ix_user_creatures_for_sale'))
        batch_op.drop_index(batch_op.f('ix_user_creatures_user_id'))

    with op.batch_alter_table('user_pet_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pet_items_user_id'))

    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_products_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_house'))
        batch_op.drop_index(batch_op.f('ix_users_name'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_house'), ['house'], unique=False)

    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_products_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_pet_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pet_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_creatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_creatures_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_creatures_for_sale'), ['for_sale'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_creatures_creature_id'), ['creature_id'], unique=False)

    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.alter_column('foil',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_shop_category'), ['shop', 'category'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('post_reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reposts_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_likes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_likes_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id_read'), ['user_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id_created_at'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_receiver_unread'), ['sender_id', 'receiver_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_sender_id_receiver_id_created_at'), ['sender_id', 'receiver_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id_unread'), ['room_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_room_id_read'), ['room_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id_created_at'), ['room_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id_unread'), ['receiver_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_pinned_true'), ['pinned'], unique=False, sqlite_where=sa.text('pinned = 1'))
        batch_op.create_index(batch_op.f('ix_messages_pinned'), ['pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_requests_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_requests_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_threads_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('forum_thread_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_thread_votes_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_comments_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('chat_room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_room_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_room_members_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('article_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_subscriptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('article_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_comments_article_id'), ['article_id'], unique=False)

    op.create_table('_alembic_tmp_user_cards',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('album_id', sa.VARCHAR(), nullable=False),
    sa.Column('card_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('foil', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['album_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name=op.f('uq_user_card'))
    )
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_user_id'))
        batch_op.drop_index('ix_fcm_tokens_user_active')
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_token'))

    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###