"""add reactions table

Revision ID: 6dd79fb02829
Revises: 8c95ce3f8f3c
Create Date: 2026-08-11 20:10:11.594004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd79fb02829'
down_revision: Union[str, None] = '8c95ce3f8f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'user_id', 'emoji', name='uq_reactions_target_user_emoji')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index('ix_reactions_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('ix_reactions_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reactions_user')
        batch_op.drop_index('ix_reactions_target')

    op.drop_table('reactions')
    # ### end Alembic commands ###