"""add media fields to comments

Revision ID: b20b89ff5194
Revises: 48c91a54afa5
Create Date: 2026-08-20 15:00:35.530374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20b89ff5194'
down_revision: Union[str, None] = '48c91a54afa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_poster_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_article_comments_article_id'))

    with op.batch_alter_table('article_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_subscriptions_user_id'))

    with op.batch_alter_table('chat_room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_room_members_room_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_members_user_id'))

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_poster_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_forum_comments_thread_id'))

    with op.batch_alter_table('forum_thread_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_thread_votes_thread_id'))

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_threads_author_id'))

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_requests_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_friend_requests_sender_id'))

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_pinned'))
        batch_op.drop_index(batch_op.f('ix_messages_pinned_true'), sqlite_where=sa.text('pinned = 1'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id_unread'), sqlite_where=sa.text('read = 0'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_read'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id_unread'), sqlite_where=sa.text('read = 0'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id_receiver_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_receiver_unread'), sqlite_where=sa.text('read = 0'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id_read'))

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_poster_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_likes_user_id'))

    with op.batch_alter_table('post_reposts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reposts_post_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_shop_category'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_sender_id'))

    with op.batch_alter_table('user_creatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_creatures_creature_id'))
        batch_op.drop_index(batch_op.f('ix_user_creatures_for_sale'))
        batch_op.drop_index(batch_op.f('ix_user_creatures_user_id'))

    with op.batch_alter_table('user_pet_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pet_items_user_id'))

    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_products_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_house'))
        batch_op.drop_index(batch_op.f('ix_users_name'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_house'), ['house'], unique=False)

    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_products_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_pet_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pet_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_creatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_creatures_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_creatures_for_sale'), ['for_sale'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_creatures_creature_id'), ['creature_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_shop_category'), ['shop', 'category'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('post_reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reposts_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_likes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_likes_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)
        batch_op.drop_column('video_duration')
        batch_op.drop_column('video_poster_url')
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id_read'), ['user_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id_created_at'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_receiver_unread'), ['sender_id', 'receiver_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_sender_id_receiver_id_created_at'), ['sender_id', 'receiver_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id_unread'), ['room_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_room_id_read'), ['room_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id_created_at'), ['room_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id_unread'), ['receiver_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_pinned_true'), ['pinned'], unique=False, sqlite_where=sa.text('pinned = 1'))
        batch_op.create_index(batch_op.f('ix_messages_pinned'), ['pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_requests_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_requests_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_threads_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('forum_thread_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_thread_votes_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_comments_thread_id'), ['thread_id'], unique=False)
        batch_op.drop_column('video_duration')
        batch_op.drop_column('video_poster_url')
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('chat_room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_room_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_room_members_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('article_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_subscriptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('article_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_comments_article_id'), ['article_id'], unique=False)
        batch_op.drop_column('video_duration')
        batch_op.drop_column('video_poster_url')
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###