"""album de figuritas

Revision ID: bfb81e982ed0
Revises: 244b28323747
Create Date: 2026-08-13 13:16:42.453506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb81e982ed0'
down_revision: Union[str, None] = '244b28323747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_zerines', sa.Integer(), nullable=False),
    sa.Column('num_cards', sa.Integer(), nullable=False),
    sa.Column('rarity_weights', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_rewards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pack_type_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_rewards_user_id'), ['user_id'], unique=False)

    op.create_table('albums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roulette_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cost_zerines', sa.Integer(), nullable=False),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roulette_spins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roulette_spins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roulette_spins_user_id'), ['user_id'], unique=False)

    op.create_table('album_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'slot_number', name='uq_album_slot')
    )
    with op.batch_alter_table('album_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_cards_album_id'), ['album_id'], unique=False)

    op.create_table('user_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pack_type_id', sa.String(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_packs_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_packs_user_id'), ['user_id'], unique=False)

    op.create_table('user_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['album_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card')
    )
    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_cards_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cards_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_cards_card_id'))
        batch_op.drop_index(batch_op.f('ix_user_cards_album_id'))

    op.drop_table('user_cards')
    with op.batch_alter_table('user_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_packs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_packs_album_id'))

    op.drop_table('user_packs')
    with op.batch_alter_table('album_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_cards_album_id'))

    op.drop_table('album_cards')
    with op.batch_alter_table('roulette_spins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roulette_spins_user_id'))

    op.drop_table('roulette_spins')
    op.drop_table('roulette_configs')
    op.drop_table('albums')
    with op.batch_alter_table('admin_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_rewards_user_id'))

    op.drop_table('admin_rewards')
    op.drop_table('pack_types')
    # ### end Alembic commands ###